version: "3"

services:
    nhentai_archivist:
        container_name: "nhentai_archivist"
        image: "ghcr.io/9-fs/nhentai_archivist:3.0.1"
        environment:
            HOST_OS: "Unraid"
            PGID: 100
            PUID: 99
            TZ: "UTC"
            UMASK: 000
        volumes:
            - "/mnt/user/appdata/nhentai_archivist/config/:/app/config/:rw"
            - "/mnt/user/appdata/nhentai_archivist/db/:/app/db/:rw"
            - "/mnt/user/appdata/nhentai_archivist/log/:/app/log/:rw"
            - "/mnt/user/media/hentai/:/app/hentai/:rw"
        network_mode: "bridge"
        deploy:
            resources:
                limits:
                    memory: "1G"
        user: "99:100"

networks: {}